name: Server tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
      - name: Set up Python 3.11
        run: uv python install
      - name: Install dependencies
        run: |
          uv tool install git-annex
          uv tool install datalad
          uv venv
          uv pip install -r requirements-devel.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run flake8 . --exclude .venv --count --ignore E501,E722,E402 --show-source --statistics
      - name: Test with pytest
        run: |
          git config --global user.email "github-test@example.com"
          git config --global user.name "Github Testscript"
          uv run pytest
